name: Generate .keystore

on:
  workflow_dispatch:
    inputs:
      alias:
        type: string
        description: Alias (anything you want)
      name:
        type: string
        description: Your Name
      organization:
        type: string
        description: Organization Name
      locality:
        type: string
        description: Locality / City
      state:
        type: string
        description: State / Province
      country:
        type: string
        description: Country (2 letter code)
      save-secrets:
        description: "Save secrets"
        type: choice
        default: 'true'
        options:
          - true
          - false
      upload-artifact:
        description: "Get an artifact to download"
        type: choice
        default: 'false'
        options:
          - true
          - false

jobs:
  setup:
    uses: starburst997/unity-github-actions/.github/workflows/keystore.yml@v1
    secrets: inherit
    with:
      alias: ${{ inputs.alias }}
      name: ${{ inputs.name }}
      organization: ${{ inputs.organization }}
      locality: ${{ inputs.locality }}
      state: ${{ inputs.state }}
      country: ${{ inputs.country }}
      save-secrets: ${{ inputs.save-secrets }}
      upload-artifact: ${{ inputs.upload-artifact }}